### ISSUE TITLE
Include binaries for 32bit ARM chips

### ISSUE THREAD

**Issue by dimo414** [peppys/crib#8]
It'd be nice to include a 32bit ARM binary alongside the 64bit one, which would make it easier to install this project on older Raspberry Pi's (among other devices).

**Comment by peppys** [comment]
Thanks for reporting! This _should_ be resolved moving forward, starting with release [1.0.6](https://github.com/peppys/crib/releases/tag/1.0.6). The assets with 32 bit ARM binaries are labeled with the suffix `armv6`. For example: `crib_Linux_armv6.tar.gz`. I don't have a physical device to test this with, so please me know if you notice anything wonky.
