### ISSUE TITLE
Provide a --csv option or similar machine-readable output format

### ISSUE THREAD

**Issue by dimo414** [peppys/crib#9]
It would be nice to provide a machine-readable output format alongside the default human-readable format. Easiest would be to accept a `--csv` flag and output the table as CSV, but JSON or another machine-readable format would be fine too.

**Comment by peppys** [comment]
Thanks for the feature request! This is now a supported feature as of [v2.0.1](https://github.com/peppys/crib/releases/tag/2.0.1), with support for `json` and `csv` formats.

**Comment by dimo414** [comment]
Thanks for the quick fix! Consider removing the CRIB ASCII art from the new formats (or providing a flag to turn it off); it's cute but noisy and currently the only option is to discard stderr which would hide errors too.

**Comment by peppys** [comment]
No problem!

Yeah I definitely cheated 😇 by sending the ASCII art to stderr to enable redirecting the json/csv output.

Adding a flag to turn off the ASCII art is a good idea 👍
